# 4.2 Universal Function (ufunc)

ufunc는 정해진 개수의 스칼라 입력을 받아서 하나 이상의 스칼라 결과 값을 반환하는 함수이다.
Numpy에서는 ndarray의 데이터를 데이터 원소별로 연산을 수행하는 함수를 의미한다.

In [8]:
import numpy as np

## 4.2.1 Uninomial Universal Function

단항 유니버설 함수는 하나의 ndarray 값을 받아서 그 결과를 반환한다.

### 1) abs, fabs

각 원소의 절대값을 구한다.

In [9]:
data = np.random.rand(2, 3) * 2 - 1

In [10]:
data

array([[ 0.66684774,  0.50114219,  0.56886496],
       [ 0.73428689,  0.03746662, -0.72624672]])

In [11]:
np.abs(data)

array([[ 0.66684774,  0.50114219,  0.56886496],
       [ 0.73428689,  0.03746662,  0.72624672]])

In [12]:
np.fabs(data)

array([[ 0.66684774,  0.50114219,  0.56886496],
       [ 0.73428689,  0.03746662,  0.72624672]])

fabs와 abs의 차이는?

### 2) sqrt, square

sqrt는 각 원소의 제곱근을, square은 각 원소의 제곱을 구한다.

In [13]:
data = np.random.randint(1, 10, size=(2,3))

In [14]:
data

array([[7, 5, 3],
       [2, 2, 1]])

In [15]:
np.sqrt(data)

array([[ 2.64575131,  2.23606798,  1.73205081],
       [ 1.41421356,  1.41421356,  1.        ]])

In [16]:
np.square(data)

array([[49, 25,  9],
       [ 4,  4,  1]])

### 3) Exp

각 원소에서 e^x을 구한다.

In [17]:
data = np.random.rand(2,3)

In [18]:
data

array([[ 0.33081964,  0.11478218,  0.48057529],
       [ 0.11457151,  0.8893196 ,  0.90705004]])

In [19]:
np.exp(data)

array([[ 1.39210869,  1.1216291 ,  1.61700439],
       [ 1.12139283,  2.43347336,  2.47700467]])

In [20]:
np.exp(1)

2.7182818284590451

### 4) log, log10, log2, log1p

In [21]:
순서대로 자연로그, 로그10, 로그2, 자연로그(1+x)를 구한다.

SyntaxError: invalid syntax (<ipython-input-21-4ebe422e1b23>, line 1)

In [22]:
data = np.random.rand(2,3)

In [23]:
data

array([[ 0.49223888,  0.48517527,  0.23618772],
       [ 0.09635213,  0.58863945,  0.27250539]])

In [24]:
np.log(data)

array([[-0.70879116, -0.72324508, -1.44312838],
       [-2.33974576, -0.52994142, -1.3000969 ]])

In [25]:
np.log10(data)

array([[-0.30782409, -0.31410135, -0.62674269],
       [-1.01613867, -0.23015063, -0.56462491]])

In [26]:
np.log2(data)

array([[-1.02256949, -1.04342209, -2.08199416],
       [-3.37553961, -0.76454386, -1.87564335]])

In [27]:
np.log1p(data)

array([[ 0.40027759,  0.39553279,  0.21203222],
       [ 0.09198842,  0.46287796,  0.2409877 ]])

In [28]:
np.log((data+1))

array([[ 0.40027759,  0.39553279,  0.21203222],
       [ 0.09198842,  0.46287796,  0.2409877 ]])

### 5) sign

각 원소의 부호를 계산한다. 양수는 1, 음수는 -1, 0은 0으로 출력한다.

In [29]:
data = np.random.rand(2,3)*2-1

In [30]:
data

array([[-0.96498222,  0.97781172,  0.79445252],
       [ 0.34334154, -0.77928911,  0.5701729 ]])

In [31]:
np.sign(data)

array([[-1.,  1.,  1.],
       [ 1., -1.,  1.]])

### 6) ceil

각 원소 소수자리를 올린다. 각 원소보다 같거나 더 큰 정수 중 가장 작은 정수를 반환한다.

In [32]:
data = np.random.rand(2,3) * 3

In [33]:
data

array([[ 1.44299679,  2.48938803,  1.90302441],
       [ 0.67920762,  2.2373276 ,  0.1433522 ]])

In [34]:
np.ceil(data)

array([[ 2.,  3.,  2.],
       [ 1.,  3.,  1.]])

### 7) floor

각 원소자리의 소수자리를 내린다. 각 원소보다 같거나 더 작은 정수 중 가장 큰 정수를 반환한다.

In [35]:
data = np.random.rand(2,3) * 3

In [36]:
data

array([[ 1.67528674,  0.91796584,  2.10903772],
       [ 0.6488194 ,  0.75901419,  2.85088865]])

In [37]:
np.floor(data)

array([[ 1.,  0.,  2.],
       [ 0.,  0.,  2.]])

### 8) rint

각 원소의 소수자리를 반올림한다. data type은 유지된다.

In [38]:
data = np.random.rand(2,3) * 3

In [39]:
data

array([[ 0.34056695,  2.96145539,  0.00823862],
       [ 2.32091531,  1.84775821,  0.67622273]])

In [40]:
np.rint(data)

array([[ 0.,  3.,  0.],
       [ 2.,  2.,  1.]])

### 9) modf

In [41]:
data = np.random.rand(2,3) * 3

In [42]:
data

array([[ 2.71035494,  1.71133691,  0.26020664],
       [ 1.31296346,  1.93590584,  2.17565903]])

In [43]:
np.modf(data)

(array([[ 0.71035494,  0.71133691,  0.26020664],
        [ 0.31296346,  0.93590584,  0.17565903]]), array([[ 2.,  1.,  0.],
        [ 1.,  1.,  2.]]))

In [44]:
remainder, portion = np.modf(data)

In [45]:
portion

array([[ 2.,  1.,  0.],
       [ 1.,  1.,  2.]])

In [46]:
remainder

array([[ 0.71035494,  0.71133691,  0.26020664],
       [ 0.31296346,  0.93590584,  0.17565903]])

### 10) isnan, isfinite, isinf

isnan: 각 원소가 숫자인지 아닌지 알려주는 불리언 배열을 반환한다.  
isfinite: 각 원소가 유한한 값인지 알려주는 불리언 배열을 반환한다.  
isinf: 각 원소가 무한한 값인지 알려주는 불리언 배열을 반환한다.  

In [47]:
data = ([np.log(-1),1.5,np.log(0.1)])

/Users/wonjae/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in log
  if __name__ == '__main__':


In [48]:
data

[nan, 1.5, -2.3025850929940455]

In [49]:
np.isnan(data)

array([ True, False, False], dtype=bool)

In [50]:
data.append(np.inf)

In [51]:
data

[nan, 1.5, -2.3025850929940455, inf]

In [52]:
np.isfinite(data)

array([False,  True,  True, False], dtype=bool)

In [53]:
np.isinf(data)

array([False, False, False,  True], dtype=bool)

### 11) cos, cosh, sin, sinh, tan, tanh

일반 삼각 함수와 쌍곡삼각 함수

In [54]:
data = np.random.rand(2,3)

In [55]:
data

array([[ 0.82205774,  0.40875692,  0.06046201],
       [ 0.19455226,  0.23187862,  0.92293655]])

In [56]:
np.cos(data)

array([[ 0.68071525,  0.91761562,  0.99817273],
       [ 0.98113433,  0.97323639,  0.60348122]])

In [57]:
np.cosh(data)

array([[ 1.35735152,  1.08471079,  1.00182838],
       [ 1.01898506,  1.02700452,  1.45701018]])

In [58]:
np.sin(data)

array([[ 0.73254812,  0.39746896,  0.06042518],
       [ 0.19332726,  0.22980627,  0.79737721]])

In [59]:
np.sinh(data)

array([[ 0.91782523,  0.42023506,  0.06049886],
       [ 0.19578191,  0.23396215,  1.05965969]])

In [60]:
np.tan(data)

array([[ 1.07614471,  0.4331541 ,  0.0605358 ],
       [ 0.19704464,  0.23612585,  1.3212958 ]])

In [61]:
np.tanh(data)

array([[ 0.67618831,  0.38741668,  0.06038844],
       [ 0.19213423,  0.22781024,  0.72728366]])

### 12) arccos, arccosh, arcsin, arcsinh, arctan, arctanh

역삼각 함수

In [62]:
data = np.random.rand(2,3)

In [63]:
np.arccos(data)


array([[ 1.20529064,  1.2787564 ,  1.24490753],
       [ 0.78716125,  1.16810254,  1.03866454]])

In [64]:
np.arccosh(data+1)

array([[ 0.82213412,  0.74170469,  0.78024578],
       [ 1.12748159,  0.85869638,  0.96898798]])

In [65]:
np.arcsin(data)

array([[ 0.36550569,  0.29203993,  0.32588879],
       [ 0.78363508,  0.40269378,  0.53213179]])

In [66]:
np.arcsinh(data)

array([[ 0.35021838,  0.28407038,  0.31491972],
       [ 0.65745983,  0.3825024 ,  0.48779537]])

In [67]:
np.arctan(data)

array([[ 0.34327115,  0.28032513,  0.30983984],
       [ 0.61464736,  0.3735025 ,  0.46952742]])

In [68]:
np.arctanh(data)

array([[ 0.37392676,  0.29628191,  0.33181526],
       [ 0.8788824 ,  0.41404054,  0.55918369]])

### 13) logical_not 

각 원소의 논리 부정 값을 계산한다.

In [69]:
data = [True, True, False, False, True]

In [70]:
data

[True, True, False, False, True]

In [71]:
np.logical_not(data)

array([False, False,  True,  True, False], dtype=bool)

## Binomial Universial Function

### 1) add, subtract, multiply

두 배열을 입력받아 같은 위치의 원소끼리 더하고 빼고 곱한다.  
배열의 차원과 크기는 동일해야한다.

In [114]:
data1 = np.random.rand(2,3)

In [115]:
data1

array([[ 0.15211915,  0.96927237,  0.76852026],
       [ 0.03065946,  0.16689947,  0.25963641]])

In [116]:
data2 = np.random.rand(2,3)

In [117]:
data2

array([[ 0.70298194,  0.12515509,  0.43878514],
       [ 0.13133496,  0.69355623,  0.98038212]])

In [118]:
np.add(data1, data2)

array([[ 0.85510109,  1.09442746,  1.2073054 ],
       [ 0.16199442,  0.8604557 ,  1.24001853]])

In [119]:
np.subtract(data1, data2)

array([[-0.55086278,  0.84411727,  0.32973512],
       [-0.10067549, -0.52665676, -0.72074571]])

In [120]:
np.multiply(data1, data2)

array([[ 0.10693702,  0.12130937,  0.33721527],
       [ 0.00402666,  0.11575417,  0.25454289]])

### 2) divide, floor_divide

첫 번째 배열의 원소에서 두 번째 배열의 원소를 나눈다.  
floor_divide는 나눈 몫만 가진다.

In [125]:
data1 = np.random.randint(1,10,size=(2,3))

In [126]:
data1

array([[2, 1, 8],
       [1, 8, 2]])

In [128]:
data2 = np.random.randint(1,10,size=(2,3))

In [129]:
data2

array([[1, 4, 2],
       [9, 6, 2]])

In [130]:
np.divide(data1, data2)

array([[ 2.        ,  0.25      ,  4.        ],
       [ 0.11111111,  1.33333333,  1.        ]])

In [131]:
np.floor_divide(data1, data2)

array([[2, 0, 4],
       [0, 1, 1]])

### 3) power

첫 번째 원소에서 두 번째 배열의 원소만큼 제곱한다.

In [132]:
data1 = np.random.randint(1,10,size=(2,3))

In [138]:
data1

array([[6, 7, 5],
       [7, 6, 7]])

In [142]:
data2 = np.random.randint(1,10,size=(2,3))

In [143]:
data2

array([[5, 2, 9],
       [4, 6, 1]])

In [144]:
np.power(data1, data2)

array([[   7776,      49, 1953125],
       [   2401,   46656,       7]])

### 4) maximum, minimum

배열의 같은 위치에 있는 두 원소 중 큰 값 또는 작은 값을 반환한다.

In [146]:
data1 = np.random.randint(1,10,size=(2,3))

In [148]:
data1

array([[6, 2, 6],
       [5, 5, 6]])

In [149]:
data2 = np.random.randint(1,10,size=(2,3))

In [150]:
data2

array([[3, 7, 6],
       [3, 4, 1]])

In [151]:
np.maximum(data1, data2)

array([[6, 7, 6],
       [5, 5, 6]])

In [152]:
np.minimum(data1, data2)

array([[3, 2, 6],
       [3, 4, 1]])

### 5) mod

첫 번째 배열의 각 원소를 두 번째 배열의 원소로 나눈 나머지 값을 구한다.  
floor_divide와 함께 이용하면 몫과 나머지를 구할 수 있다.

In [154]:
data1 = np.random.randint(1,10,size=(2,3))

In [155]:
data1

array([[9, 6, 4],
       [5, 6, 3]])

In [156]:
data2 = np.random.randint(1,10,size=(2,3))

In [157]:
data2

array([[8, 5, 3],
       [3, 4, 8]])

In [158]:
np.mod(data1, data2)

array([[1, 1, 1],
       [2, 2, 3]])

### 6) copysign

첫 번째 배열의 원소의 부호를 두 번째 배열의 원소 부호로 바꿔준다.

In [159]:
data1 = np.random.randint(-5,5,size=(2,3))

In [160]:
data1

array([[-2,  4, -3],
       [ 0, -5, -2]])

In [161]:
data2 = np.random.randint(-5,5,size=(2,3))

In [162]:
data2

array([[ 2,  4, -5],
       [ 4,  1, -3]])

In [163]:
np.copysign(data1, data2)

array([[ 2.,  4., -3.],
       [ 0.,  5., -2.]])

### 7) greater, greater_equal, less, less_equal, equal,  not_equal

In [ ]:
두 배열의 각 원소간의 >, >=, <, <=, ==, != 비교연산 결과를 반환한다.

In [164]:
data1 = np.random.randint(-5,5,size=(2,3))

In [165]:
data1

array([[-1,  1, -1],
       [ 4,  3, -2]])

In [166]:
data2 = np.random.randint(-5,5,size=(2,3))

In [167]:
data2

array([[-3, -5,  0],
       [ 3,  2,  1]])

In [168]:
np.greater(data1, data2)

array([[ True,  True, False],
       [ True,  True, False]], dtype=bool)

### 8) logical_and, logical_or, logical_xor

두 배열의 각 원소 간의 논리연산 결과를 반환한다.

In [170]:
data1 = [True, True, False, True]

In [172]:
data2 = [True,False,False,True]

In [173]:
np.logical_and(data1,data2)

array([ True, False, False,  True], dtype=bool)

In [174]:
np.logical_or(data1, data2)

array([ True,  True, False,  True], dtype=bool)

In [175]:
np.logical_xor(data1,data2)

array([False,  True, False, False], dtype=bool)