# 4.2 Universal Function (ufunc)

ufunc는 정해진 개수의 스칼라 입력을 받아서 하나 이상의 스칼라 결과 값을 반환하는 함수이다.
Numpy에서는 ndarray의 데이터를 데이터 원소별로 연산을 수행하는 함수를 의미한다.

제공하는 기능들로는 다음과 같은 것이 있다.


* array broadcasting
* type casting

In [1]:
import numpy as np

## 4.2.1 Uninomial Universal Function

단항 유니버설 함수는 하나의 ndarray 값을 받아서 그 결과를 반환한다.

### 1) abs, fabs

각 원소의 절대값을 구한다.

In [7]:
data = np.random.rand(2, 3) * 2 - 1

In [8]:
data

array([[ 0.97054751, -0.20310257, -0.26989838],
       [-0.29687211, -0.68404651,  0.5859228 ]])

In [10]:
np.abs(data)

array([[ 0.97054751,  0.20310257,  0.26989838],
       [ 0.29687211,  0.68404651,  0.5859228 ]])

In [11]:
np.fabs(data)

array([[ 0.97054751,  0.20310257,  0.26989838],
       [ 0.29687211,  0.68404651,  0.5859228 ]])

fabs와 abs의 차이는?

### 2) sqrt, square

sqrt는 각 원소의 제곱근을, square은 각 원소의 제곱을 구한다.

In [14]:
data = np.random.randint(1, 10, size=(2,3))

In [15]:
data

array([[5, 6, 2],
       [4, 5, 1]])

In [16]:
np.sqrt(data)

array([[ 2.23606798,  2.44948974,  1.41421356],
       [ 2.        ,  2.23606798,  1.        ]])

In [17]:
np.square(data)

array([[25, 36,  4],
       [16, 25,  1]])

### 3) Exp

각 원소에서 e^x을 구한다.

In [18]:
data = np.random.rand(2,3)

In [19]:
data

array([[ 0.3783773 ,  0.75228942,  0.55293911],
       [ 0.55828068,  0.88006278,  0.45397831]])

In [20]:
np.exp(data)

array([[ 1.45991366,  2.12185227,  1.73835473],
       [ 1.74766512,  2.41105107,  1.57456385]])

In [21]:
np.exp(1)

2.7182818284590451

### 4) log, log10, log2, log1p

In [ ]:
순서대로 자연로그, 로그10, 로그2, 자연로그(1+x)를 구한다.

In [22]:
data = np.random.rand(2,3)

In [23]:
data

array([[ 0.18826054,  0.6052645 ,  0.66087422],
       [ 0.70152498,  0.87931909,  0.99840961]])

In [24]:
np.log(data)

array([[ -1.66992841e+00,  -5.02089721e-01,  -4.14191750e-01],
       [ -3.54498770e-01,  -1.28607430e-01,  -1.59165708e-03]])

In [25]:
np.log10(data)

array([[ -7.25240693e-01,  -2.18054795e-01,  -1.79881191e-01],
       [ -1.53956859e-01,  -5.58534970e-02,  -6.91247886e-04]])

In [26]:
np.log2(data)

array([[ -2.40919743e+00,  -7.24362351e-01,  -5.97552383e-01],
       [ -5.11433617e-01,  -1.85541301e-01,  -2.29627577e-03]])

In [27]:
np.log1p(data)

array([[ 0.17249051,  0.47328854,  0.5073441 ],
       [ 0.5315249 ,  0.63090953,  0.69235167]])

In [29]:
np.log((data+1))

array([[ 0.17249051,  0.47328854,  0.5073441 ],
       [ 0.5315249 ,  0.63090953,  0.69235167]])

### 5) sign

각 원소의 부호를 계산한다. 양수는 1, 음수는 -1, 0은 0으로 출력한다.

In [32]:
data = np.random.rand(2,3)*2-1

In [33]:
data

array([[ 0.48966274,  0.56112474, -0.81010995],
       [-0.3375061 , -0.84639808, -0.98538509]])

In [34]:
np.sign(data)

array([[ 1.,  1., -1.],
       [-1., -1., -1.]])

### 6) ceil

각 원소 소수자리를 올린다. 각 원소보다 같거나 더 큰 정수 중 가장 작은 정수를 반환한다.

In [41]:
data = np.random.rand(2,3) * 3

In [42]:
data

array([[ 1.114536  ,  1.19675926,  2.07199669],
       [ 2.8336545 ,  1.50860902,  1.11155009]])

In [43]:
np.ceil(data)

array([[ 2.,  2.,  3.],
       [ 3.,  2.,  2.]])

### 7) floor

각 원소자리의 소수자리를 내린다. 각 원소보다 같거나 더 작은 정수 중 가장 큰 정수를 반환한다.

In [44]:
data = np.random.rand(2,3) * 3

In [45]:
data

array([[ 2.33961713,  0.78689373,  1.53391311],
       [ 0.89564796,  1.28395175,  0.66966032]])

In [46]:
np.floor(data)

array([[ 2.,  0.,  1.],
       [ 0.,  1.,  0.]])

### 8) rint

각 원소의 소수자리를 반올림한다. data type은 유지된다.

In [47]:
data = np.random.rand(2,3) * 3

In [48]:
data

array([[ 0.60083804,  1.08365548,  1.90794525],
       [ 0.58814927,  2.85203251,  2.83413799]])

In [49]:
np.rint(data)

array([[ 1.,  1.,  2.],
       [ 1.,  3.,  3.]])

### 9) modf

In [50]:
data = np.random.rand(2,3) * 3

In [51]:
data

array([[ 1.01120782,  1.54449407,  0.12613798],
       [ 1.30392147,  2.98284573,  1.30628338]])

In [52]:
np.modf(data)

(array([[ 0.01120782,  0.54449407,  0.12613798],
        [ 0.30392147,  0.98284573,  0.30628338]]), array([[ 1.,  1.,  0.],
        [ 1.,  2.,  1.]]))

In [59]:
remainder, portion = np.modf(data)

In [60]:
portion

array([[ 1.,  1.,  0.],
       [ 1.,  2.,  1.]])

In [61]:
remainder

array([[ 0.01120782,  0.54449407,  0.12613798],
       [ 0.30392147,  0.98284573,  0.30628338]])

### 10) isnan, isfinite, isinf

isnan: 각 원소가 숫자인지 아닌지 알려주는 불리언 배열을 반환한다.  
isfinite: 각 원소가 유한한 값인지 알려주는 불리언 배열을 반환한다.  
isinf: 각 원소가 무한한 값인지 알려주는 불리언 배열을 반환한다.  

In [96]:
data = ([np.log(-1),1.5,np.log(0.1)])

/Users/wonjae/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in log
  if __name__ == '__main__':


In [97]:
data

[nan, 1.5, -2.3025850929940455]

In [98]:
np.isnan(data)

array([ True, False, False], dtype=bool)

In [99]:
data.append(np.inf)

In [100]:
data

[nan, 1.5, -2.3025850929940455, inf]

In [101]:
np.isfinite(data)

array([False,  True,  True, False], dtype=bool)

In [102]:
np.isinf(data)

array([False, False, False,  True], dtype=bool)

### 11) cos, cosh, sin, sinh, tan, tanh

일반 삼각 함수와 쌍곡삼각 함수

In [105]:
data = np.random.rand(2,3)

In [106]:
data

array([[ 0.27621139,  0.23776194,  0.57720248],
       [ 0.34562802,  0.23984293,  0.66412956]])

In [104]:
np.cos(data)

array([[ 0.98952834,  0.56053283,  0.98903063],
       [ 0.96703931,  0.99727309,  0.9531393 ]])

In [107]:
np.cosh(data)

array([[ 1.03838951,  1.02839878,  1.17125791],
       [ 1.06032634,  1.02890046,  1.22876003]])

In [108]:
np.sin(data)

array([[ 0.27271261,  0.23552812,  0.54568177],
       [ 0.33878763,  0.23755005,  0.61637394]])

In [109]:
np.sinh(data)

array([[ 0.27973697,  0.24000843,  0.60979102],
       [ 0.35255062,  0.24214903,  0.71403867]])

In [110]:
np.tan(data)

array([[ 0.28345689,  0.24234591,  0.65117741],
       [ 0.36008183,  0.24455023,  0.78274319]])

In [111]:
np.tanh(data)

array([[ 0.26939503,  0.2333807 ,  0.52062916],
       [ 0.33249257,  0.23534738,  0.58110506]])

### 12) arccos, arccosh, arcsin, arcsinh, arctan, arctanh

역삼각 함수

In [124]:
data = np.random.rand(2,3)

In [125]:
np.arccos(data)


array([[ 1.2374816 ,  1.2410105 ,  0.43559591],
       [ 0.29078889,  1.35167447,  1.3622084 ]])

In [126]:
np.arccosh(data+1)

array([[ 0.78834779,  0.78451267,  1.2612829 ],
       [ 1.29237307,  0.64795725,  0.63293269]])

In [127]:
np.arcsin(data)

array([[ 0.33331473,  0.32978582,  1.13520042],
       [ 1.28000743,  0.21912186,  0.20858792]])

In [117]:
np.arcsinh(data)

array([[  8.77772705e-01,   7.80524906e-01,   3.57366659e-01],
       [  3.72980982e-02,   6.41419524e-01,   4.39897722e-04]])

In [118]:
np.arctan(data)

array([[  7.82848713e-01,   7.11549256e-01,   3.49994254e-01],
       [  3.72894533e-02,   6.01482382e-01,   4.39897708e-04]])

In [119]:
np.arctanh(data)

array([[  2.98593775e+00,   1.30195693e+00,   3.82667717e-01],
       [  3.73240689e-02,   8.40956245e-01,   4.39897764e-04]])

### 13) logical_not 

각 원소의 논리 부정 값을 계산한다.

In [70]:
data = [True, True, False, False, True]

In [71]:
data

[True, True, False, False, True]

In [72]:
np.logical_not(data)

array([False, False,  True,  True, False], dtype=bool)