In [1]:
import numpy as np

NumPy(Numerical Python)의 줄임말인 NumPy는 고성능의 과학계산 컴퓨팅과 데이터 분석에 필요한 기본 패키지다.
NumPy에서 제공되는 기능은 다음과 같다.

- 빠르고 메모리를 효율적으로 사용하며, 벡터 산술연산과 세련된 브로드캐스팅 기능을 제공하는 다차원 배열인 ndarry
- 반복문을 작성할 필요 없이 전체 데이터 배열에 대해 빠른 연산을 제공하는 표준 수학 함수
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 올려진 파일을 사용하는 도구
- 선형대수, 난수 발생기, 푸리에 변환 기능
- C, C++, 포트란으로 쓰여진 코드를 통합하는 도구

# 4.1 NumPy ndarray : 다차원 배열 객체

In [2]:
data = np.random.rand(2, 3)
data

array([[ 0.68689391,  0.8543871 ,  0.86302769],
       [ 0.74417204,  0.86906325,  0.65269569]])

In [3]:
data * 10

array([[ 6.86893905,  8.54387099,  8.63027691],
       [ 7.4417204 ,  8.6906325 ,  6.52695689]])

In [4]:
data + 10

array([[ 10.68689391,  10.8543871 ,  10.86302769],
       [ 10.74417204,  10.86906325,  10.65269569]])

In [5]:
data * data

array([[ 0.47182324,  0.72997732,  0.74481679],
       [ 0.55379202,  0.75527093,  0.42601166]])

In [6]:
data + data

array([[ 1.37378781,  1.7087742 ,  1.72605538],
       [ 1.48834408,  1.7381265 ,  1.30539138]])

##  4.1.1 ndarray 생성

In [28]:
# ndarray 생성방법 : 배열 주입
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [8]:
# ndarray 생성방법 : 2차원 배열 주입
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
# 배열의 차원을 보여준다.
arr2.ndim

2

In [10]:
# 행과 열의 개수를 보여준다.
arr2.shape

(2, 4)

In [29]:
# 배열 원소의 자료형을 보여준다.
arr1.dtype

dtype('float64')

In [30]:
arr2.dtype

dtype('int64')

In [31]:
# ndarray 생성방법 : 0으로 채워진 1차원 배열 만들기
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [32]:
# ndarray 생성방법 : 0으로 채워진 2차원 배열 만들기
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [35]:
# ndarray 생성방법 : 초기화되지 않은 3차원 배열 만들기
np.empty((2, 3, 2))

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [36]:
# ndarray 생성방법 : 0부터 증가하는 숫자의 1차원 배열 만들기
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# 4.1.2 

In [38]:
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr1

array([ 1.,  2.,  3.])

In [40]:
arr2 = np.array([1, 2, 3], dtype = np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [41]:
arr = np.array([1, 2, 3, 4, 5])

In [52]:
arr.dtype

dtype('int64')

In [53]:
float_arr = arr.astype(np.float64)

In [54]:
float_arr.dtype

dtype('float64')

In [55]:
arr = np.arange(10)

In [56]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
arr[5]

5

In [ ]:
arr2d = np.arr